version: '3.1'

services:
  tb:
    depends_on:
      - tb-db
    build:
      context: .
    environment:
      - BOT_NAME=${BOT_NAME}
      - BOT_TOKEN=${BOT_TOKEN}
      - BOT_DB_USERNAME=${BOT_DB_USERNAME}
      - BOT_DB_PASSWORD=${BOT_DB_PASSWORD}
    restart: always
  tb-db:
    image: postgres
    restart: always
    environment:
      - POSTGRES_USER=${BOT_DB_USERNAME}
      - POSTGRES_PASSWORD=${BOT_DB_PASSWORD}
      - POSTGRES_DB=tb_db
    ports:
    - '5438:5432'